# Data Structure Final

## Python for Beginner

Python print

In [ ]:
print("Welcome to Python FAH Structures")
print("Welcome to Kasetsart University")
print("Welcome to Python Data Structures")

Python Variables

In [ ]:
a = 10 # a is an integer
b = 10.5 # b is a float
c = "Hello" # c is a string
d = True # d is a boolean

e = [1, 2, 3, 4, 5] # list
f = (1, 2, 3, 3, 5) # tuple
g = {"name": "John", "age": 30} # dictionary
h = {1, 2, 3, 4, 5, 6} # set

print(f"a = {a}, b = {b}, c = {c}, d = {d}")
print("a = %d, b = %f, c = %s, d = %s" % (a, b, c, d))

Arithmetic Operators

In [ ]:
a = 9
b = 3
print("Arithmetic Operators")
print("a + b = %d" % (a + b))
print("a - b = %d" % (a - b))
print("a * b = %d" % (a * b))
print("a / b = %f" % (a / b))
print("a // b = %d" % (a // b))
# print("a % b = %d" % (a % b))
print("a ** b = %d" % (a ** b))

Comparison Operators

In [ ]:
a: int = 10 
b: int = 3
print("Comparison Operators")
print(f"a > b = {a > b}")
print(f"a < b = {a < b}")
print(f"a == b = {a == b}")
print(f"a != b = {a != b}")
print(f"a >= b = {a >= b}")
print(f"a <= b = {a <= b}")

Assignments Operators

In [ ]:
print("Assignments Operators")
a = 10 
b = 3
a += b
# a = a + b
print(f"a += b = {a}")
a = 10 
b = 3
a -= b
# a = a - b
print(f"a -= b = {a}")
a = 10 
b = 3
a *= b
# a = a * b
print(f"a *= b = {a}")
a = 10 
b = 3
a /= b
# a = a / b
print(f"a /= b = {a}")
a = 10 
b = 3
a %= b
# a = a % b
print(f"a %= b = {a}")
a = 10 
b = 3
a //= b
# a = a // b
print(f"a //= b = {a}")
a = 10 
b = 3
a **= b
# a = a ** b
print(f"a **= b = {a}")

Logical Operators

In [ ]:
e = True
f = False
# e = [6,7,6,5]
# f = [6,7,1]
print("Logical Operators")
print(f"e and f = {e and f}")
print(f"e or b = {e or f}")
print(f"not e = {not e}")

Membership Operators

In [ ]:
a = 10
b = [1, 2, 3, 4, 5]
print("Membership Operators")
print(f"a in b = {a in b}")
print(f"a not in b = {a not in b}")

Identity Operators

In [ ]:
a = 10
b = 10
print("Identity Operators")
print(f"a is b = {a is b}")
print(f"a is not b = {a is not b}")

If else statement

In [ ]:
inp = int(input())
if inp > 5:
    print("inp > 5")
elif inp == 5:
    print("inp == 5")
else:
    print("inp < 5")

Loop statement

In [ ]:
for i in range(10):
    print(i, end=" ")

start = 0
stop = 10
step = 2
for i in range(start, stop, step):
    print(i)

for i in range(10):
    if i == 5:
        continue
    print(i, end=" ")

for i in range(10):
    if i == 5:
        break
    print(i, end=" ")

String slice

In [ ]:
name = "Tanapat Eiam-arj"
# print(name[0:5])
# print(name[3:5])
# print(name[0:5:2])
# print(name[0::])
print(name[-5:-1])


Lists

In [ ]:
# {} # dictionary
# {} # set
# [] # list
# () # tuple

# list
# a = [1, 2, 3, 4, 5]
# a = [5, 4, 3, 2, 1]
# a = [4, 5, 3, 1, 2, 2, 2]
# b = [5, 4, 3, 2, 1]
# a.pop()
# a.append(20)
# a.insert(1, 10)
# a.remove(6) // Value
# a.sort()
# a.reverse()
# print(a.count(2))

# Set
# a = {1, 2, 3, 4, 5}
# b = {5, 4, 3, 2, 1}
# a - b # a but not b
# a | b # a or b
# a & b # a and b
# a ^ b # a xor b

# I/O: open, close, read, write, append
# r = read
# w = write
# a = append
# r+ = read and write
# w+ = write and read
# a+ = append and read

# open = not file exist -> create file
# open = file exist -> open file

a = [4, 5, 3, 1, 2, "20", 2]
b = (10, "Anime", 3.14 , True)
print(a[0])
print(b[0])

c = {"name": "John", "age": 30}
print(c.get("name"))

Function

In [ ]:
# def hello():
    # print("Hello World")

# def hello(str):
#     print(str)

def hellos(*str):
    print(str)
def hello(**str):
    print(str)

hellos("Hello", "World", "Python")
hello(name="John", age=30, power=100)

Class

In [ ]:
class Name:
    def __init__(self, name):
        self.name = name

    def say(self):
        self.korn = 'asdasd'
        print(f"Hello {self.name}")

    def love(self):
        print(f"AAA {self.korn}")

name = Name("John")
name.say()
name.love()

In [ ]:

with open('txt.csv', 'w') as f:
    # f.write("Anime")
    for i in range(100):
        f.write(f"Anime = {i}\n")


## Python Numpy

Numpy

In [30]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
print(a) # array([1, 2, 3, 4, 5])

[1 2 3 4 5]


In [35]:
n = np.ones((5, 5) ,dtype=int)
print(n) # array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [55]:
a = np.arange(10)
print(a)

a = np.arange(0, 10)
print(a)

a = np.arange(0, 10, 2)
print(a)

a = np.arange(100, 10, -5, dtype=int)
print(a)

a = np.linspace(100, 0 ,5)
print(a)




[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[100  95  90  85  80  75  70  65  60  55  50  45  40  35  30  25  20  15]
[100.  75.  50.  25.   0.]


In [ ]:
import pandas as pd

a = np.eye(5, dtype=int)
print("np eye 5")
print(a)

a = np.eye(5, 8, dtype=int)
print("np eye 5, 8")
print(a)

a = np.eye(8, 8, -2, dtype=int)
print("np eye 5, 8, -2")
print(a)


a = np.eye(5, 8, k=1, dtype=int)
print("np eye 5, 8, k=1")
print(a)

a = np.eye(5, 8, k=-1, dtype=int)
print("np eye 5, 8, k=-1")
print(a)

a = np.eye(5, 8, k=2, dtype=int)
print("np eye 5, 8, k=2")
print(a)



In [ ]:
a = np.empty((5, 5))
# print(a)

last = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10
]

a = np.random.choice(last , p=[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05,0.05, 0.2], size=(4, 5))
print(a)

a = np.reshape(a, (5, 4))
print(a)

In [128]:
from numpy import random as rd
a = np.arange(10)
print(a)
b = rd.shuffle(a)
print(b)
c = rd.permutation(a)
print(c)

[0 1 2 3 4 5 6 7 8 9]
None
[6 8 9 7 0 1 4 3 5 2]


vactor in numpy

In [141]:
import numpy as np

L1 = [1, 2, 3, 4, 5]
L2 = [5, 4, 3, 2, 1]
L3 = np.array(L1) + np.array(L2)
print(L3)
L4 = [x+y for x, y in zip(L1, L2)]
print(L4)
L5 = lambda x, y: x+y
L5 = [x for x in L5(L1, L2)]
print(L5)

[6, 6, 6, 6, 6]
[6 6 6 6 6]


## Python: Pandas

In [3]:
import pandas as pd

In [7]:
s = pd.Series([5,20,30,35,60], index=['a','b','c','d','e'])
print(s)
print(s['a'])

a     5
b    20
c    30
d    35
e    60
dtype: int64
5
