# Data Structure Final

## Python for Beginner

Python print

In [2]:
print("Welcome to Python FAH Structures")
print("Welcome to Kasetsart University")
print("Welcome to Python Data Structures")

Welcome to Python FAH Structures
Welcome to Kasetsart University
Welcome to Python Data Structures


Python Variables

In [3]:
a = 10 # a is an integer
b = 10.5 # b is a float
c = "Hello" # c is a string
d = True # d is a boolean

e = [1, 2, 3, 4, 5] # list
f = (1, 2, 3, 3, 5) # tuple
g = {"name": "John", "age": 30} # dictionary
h = {1, 2, 3, 4, 5, 6} # set

print(f"a = {a}, b = {b}, c = {c}, d = {d}")
print("a = %d, b = %f, c = %s, d = %s" % (a, b, c, d))

a = 10, b = 10.5, c = Hello, d = True
a = 10, b = 10.500000, c = Hello, d = True


Arithmetic Operators

In [4]:
a = 9
b = 3
print("Arithmetic Operators")
print("a + b = %d" % (a + b))
print("a - b = %d" % (a - b))
print("a * b = %d" % (a * b))
print("a / b = %f" % (a / b))
print("a // b = %d" % (a // b))
# print("a % b = %d" % (a % b))
print("a ** b = %d" % (a ** b))

Arithmetic Operators
a + b = 12
a - b = 6
a * b = 27
a / b = 3.000000
a // b = 3
a ** b = 729


Comparison Operators

In [5]:
a: int = 10 
b: int = 3
print("Comparison Operators")
print(f"a > b = {a > b}")
print(f"a < b = {a < b}")
print(f"a == b = {a == b}")
print(f"a != b = {a != b}")
print(f"a >= b = {a >= b}")
print(f"a <= b = {a <= b}")

Comparison Operators
a > b = True
a < b = False
a == b = False
a != b = True
a >= b = True
a <= b = False


Assignments Operators

In [6]:
print("Assignments Operators")
a = 10 
b = 3
a += b
# a = a + b
print(f"a += b = {a}")
a = 10 
b = 3
a -= b
# a = a - b
print(f"a -= b = {a}")
a = 10 
b = 3
a *= b
# a = a * b
print(f"a *= b = {a}")
a = 10 
b = 3
a /= b
# a = a / b
print(f"a /= b = {a}")
a = 10 
b = 3
a %= b
# a = a % b
print(f"a %= b = {a}")
a = 10 
b = 3
a //= b
# a = a // b
print(f"a //= b = {a}")
a = 10 
b = 3
a **= b
# a = a ** b
print(f"a **= b = {a}")

Assignments Operators
a += b = 13
a -= b = 7
a *= b = 30
a /= b = 3.3333333333333335
a %= b = 1
a //= b = 3
a **= b = 1000


Logical Operators

In [7]:
e = True
f = False
# e = [6,7,6,5]
# f = [6,7,1]
print("Logical Operators")
print(f"e and f = {e and f}")
print(f"e or b = {e or f}")
print(f"not e = {not e}")

Logical Operators
e and f = False
e or b = True
not e = False


Membership Operators

In [8]:
a = 10
b = [1, 2, 3, 4, 5]
print("Membership Operators")
print(f"a in b = {a in b}")
print(f"a not in b = {a not in b}")

Membership Operators
a in b = False
a not in b = True


Identity Operators

In [9]:
a = 10
b = 10
print("Identity Operators")
print(f"a is b = {a is b}")
print(f"a is not b = {a is not b}")

Identity Operators
a is b = True
a is not b = False


Loop statement

In [10]:
for i in range(10):
    print(i, end=" ")

start = 0
stop = 10
step = 2
for i in range(start, stop, step):
    print(i)

for i in range(10):
    if i == 5:
        continue
    print(i, end=" ")

for i in range(10):
    if i == 5:
        break
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 0
2
4
6
8
0 1 2 3 4 6 7 8 9 0 1 2 3 4 

String slice

In [11]:
name = "Tanapat Eiam-arj"
# print(name[0:5])
# print(name[3:5])
# print(name[0:5:2])
# print(name[0::])
print(name[-5:-1])


m-ar


Lists

In [12]:
# {} # dictionary
# {} # set
# [] # list
# () # tuple

# list
# a = [1, 2, 3, 4, 5]
# a = [5, 4, 3, 2, 1]
# a = [4, 5, 3, 1, 2, 2, 2]
# b = [5, 4, 3, 2, 1]
# a.pop()
# a.append(20)
# a.insert(1, 10)
# a.remove(6) // Value
# a.sort()
# a.reverse()
# print(a.count(2))

# Set
# a = {1, 2, 3, 4, 5}
# b = {5, 4, 3, 2, 1}
# a - b # a but not b
# a | b # a or b
# a & b # a and b
# a ^ b # a xor b

# I/O: open, close, read, write, append
# r = read
# w = write
# a = append
# r+ = read and write
# w+ = write and read
# a+ = append and read

# open = not file exist -> create file
# open = file exist -> open file

a = [4, 5, 3, 1, 2, "20", 2]
b = (10, "Anime", 3.14 , True)
print(a[0])
print(b[0])

c = {"name": "John", "age": 30}
print(c.get("name"))

4
10
John


Function

In [13]:
# def hello():
    # print("Hello World")

# def hello(str):
#     print(str)

def hellos(*str):
    print(str)
def hello(**str):
    print(str)

hellos("Hello", "World", "Python")
hello(name="John", age=30, power=100)

('Hello', 'World', 'Python')
{'name': 'John', 'age': 30, 'power': 100}


Class

In [14]:
class Name:
    def __init__(self, name):
        self.name = name

    def say(self):
        self.korn = 'asdasd'
        print(f"Hello {self.name}")

    def love(self):
        print(f"AAA {self.korn}")

name = Name("John")
name.say()
name.love()

Hello John
AAA asdasd


In [15]:

with open('txt.csv', 'w') as f:
    # f.write("Anime")
    for i in range(100):
        f.write(f"Anime = {i}\n")


## Python Numpy

Numpy

In [16]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
print(a) # array([1, 2, 3, 4, 5])

[1 2 3 4 5]


In [17]:
n = np.ones((5, 5) ,dtype=int)
print(n) # array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [18]:
a = np.arange(10)
print(a)

a = np.arange(0, 10)
print(a)

a = np.arange(0, 10, 2)
print(a)

a = np.arange(100, 10, -5, dtype=int)
print(a)

a = np.linspace(100, 0 ,25, dtype=int)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[100  95  90  85  80  75  70  65  60  55  50  45  40  35  30  25  20  15]
[100  95  91  87  83  79  75  70  66  62  58  54  50  45  41  37  33  29
  25  20  16  12   8   4   0]


In [19]:
import pandas as pd

a = np.eye(5, dtype=int)
print("np eye 5")
print(a)

a = np.eye(5, 8, dtype=int)
print("np eye 5, 8")
print(a)

a = np.eye(8, 8, -2, dtype=int)
print("np eye 5, 8, -2")
print(a)


a = np.eye(5, 8, k=1, dtype=int)
print("np eye 5, 8, k=1")
print(a)

a = np.eye(5, 8, k=-1, dtype=int)
print("np eye 5, 8, k=-1")
print(a)

a = np.eye(5, 8, k=2, dtype=int)
print("np eye 5, 8, k=2")
print(a)

np eye 5
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
np eye 5, 8
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]]
np eye 5, 8, -2
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]
np eye 5, 8, k=1
[[0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]
np eye 5, 8, k=-1
[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]
np eye 5, 8, k=2
[[0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]]


In [20]:
a = np.empty((5, 5))
# print(a)

last = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]

a = np.random.choice(last , p=[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05,0.05, 0.2], size=(4, 5))
print(a)

a = np.reshape(a, (5, 4))
print(a)

[[ 4  7 10  9  5]
 [ 9  5 10 10 10]
 [10  2  1  6  7]
 [ 5  3 10 10  4]]
[[ 4  7 10  9]
 [ 5  9  5 10]
 [10 10 10  2]
 [ 1  6  7  5]
 [ 3 10 10  4]]


In [21]:
from numpy import random as rd
a = np.arange(10)
print(a)
b = rd.shuffle(a)
print(b)
c = rd.permutation(a)
print(c)

[0 1 2 3 4 5 6 7 8 9]
None
[1 6 4 8 7 0 3 5 2 9]


vactor in numpy

In [22]:
import numpy as np

L1 = [1, 2, 3, 4, 5]
L2 = [5, 4, 3, 2, 1]
L3 = np.array(L1) + np.array(L2)
print(L3)
L4 = [x+y for x, y in zip(L1, L2)]
print(L4)
L5 = lambda x, y: x+y
L5 = [x for x in L5(L1, L2)]
print(L5)

[6 6 6 6 6]
[6, 6, 6, 6, 6]
[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]


## Python: Pandas

In [23]:
import pandas as pd
import numpy as np

In [24]:
s = pd.Series([5,20,30,35,60], index=['a','b','c','d','e'])
print(f"Series\n{s}\n")

Series
a     5
b    20
c    30
d    35
e    60
dtype: int64



In [25]:
sf1 = pd.DataFrame(np.random.randint(10, 50, [5,4]))
print(f"แบบไม่กำหนด Row กับ Column\n {sf1} \n")

sf2 = pd.DataFrame(np.random.randint(10, 50, [5,4]), columns=list('abcd'), index=list('abcde'))
print(f"แบบกำหนด Row กับ Column\n {sf2} \n")

แบบไม่กำหนด Row กับ Column
     0   1   2   3
0  15  28  46  45
1  10  17  23  28
2  35  36  32  34
3  24  49  15  19
4  28  32  18  37 

แบบกำหนด Row กับ Column
     a   b   c   d
a  23  48  29  13
b  16  29  31  32
c  25  18  40  33
d  33  25  37  13
e  45  42  37  21 



Accessing Data

In [26]:
sf3 = pd.DataFrame(np.random.randint(10, 50, [5,4]), columns=list('abcd'), index=list('abcde'))
print(f"{sf3} \n")
print(f"การเข้าถึง data ใน DataFrame: sf3['a']\n{sf3['a']} \n")
print(f"การเข้าถึง data ใน DataFrame แบบเลือก Column: sf3['a'][2] \n{sf3['a'][2]} \n")
# loc
print(f"การเข้าถึง data ใน DataFrame แบบ loc: sf3.loc['a'] \n{sf3.loc['a']} \n")
print(f"การเข้าถึง data ใน DataFrame แบบ loc แบบเลือก Column: sf3.loc['a']['a']\n{sf3.loc['a']['a']} \n")
# iloc
print(f"การเข้าถึง data ใน DataFrame แบบ iloc: sf3.iloc[0] \n{sf3.iloc[0]} \n")
print(f"การเข้าถึง data ใน DataFrame แบบ iloc แบบเลือก Column: : sf3.iloc[0][0] \n{sf3.iloc[0][0]} \n")
# access
print(f"การเข้าถึง data ใน DataFrame แบบ access: sf3.a \n{sf3.a} \n")
print(f"การเข้าถึง data ใน DataFrame แบบ access แบบเลือก Column: sf3.a[0] \n{sf3.a[0]} \n")
print(f"การเข้าถึง data ใน DataFrame แบบ access แบบเลือกหลาย Column : sf3[['a','b']] \n{sf3[['a','b']]} \n")

    a   b   c   d
a  20  45  29  35
b  27  44  17  30
c  12  33  22  27
d  21  13  11  13
e  38  29  17  43 

การเข้าถึง data ใน DataFrame: sf3['a']
a    20
b    27
c    12
d    21
e    38
Name: a, dtype: int32 

การเข้าถึง data ใน DataFrame แบบเลือก Column: sf3['a'][2] 
12 

การเข้าถึง data ใน DataFrame แบบ loc: sf3.loc['a'] 
a    20
b    45
c    29
d    35
Name: a, dtype: int32 

การเข้าถึง data ใน DataFrame แบบ loc แบบเลือก Column: sf3.loc['a']['a']
20 

การเข้าถึง data ใน DataFrame แบบ iloc: sf3.iloc[0] 
a    20
b    45
c    29
d    35
Name: a, dtype: int32 

การเข้าถึง data ใน DataFrame แบบ iloc แบบเลือก Column: : sf3.iloc[0][0] 
20 

การเข้าถึง data ใน DataFrame แบบ access: sf3.a 
a    20
b    27
c    12
d    21
e    38
Name: a, dtype: int32 

การเข้าถึง data ใน DataFrame แบบ access แบบเลือก Column: sf3.a[0] 
20 

การเข้าถึง data ใน DataFrame แบบ access แบบเลือกหลาย Column : sf3[['a','b']] 
    a   b
a  20  45
b  27  44
c  12  33
d  21  13
e  38  29 



In [27]:
df = pd.DataFrame(np.arange(1,21).reshape(5,4), columns=list('WXYZ'))
print(df)

    W   X   Y   Z
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


In [28]:
print(f"\n{df.loc[1::2, 'X':'Z']}")


    X   Y   Z
1   6   7   8
3  14  15  16


In [29]:
print(f"\n{df.loc[1::2, 'X':'Z']}")


    X   Y   Z
1   6   7   8
3  14  15  16


In [30]:
print(f"\n{df[df>5]}")


      W     X     Y     Z
0   NaN   NaN   NaN   NaN
1   NaN   6.0   7.0   8.0
2   9.0  10.0  11.0  12.0
3  13.0  14.0  15.0  16.0
4  17.0  18.0  19.0  20.0


In [31]:
print(f"\n{df['W'] > 5}")
print(f"\n{df[df['W'] > 5]}")
print(f"\n{df[df['W'] > 5]['X']}")
# print(f"\n{df[df['W'] > 5].loc['X']}")
print(f"\n{df[df['W'] > 5].iloc[:, 1]}")


0    False
1    False
2     True
3     True
4     True
Name: W, dtype: bool

    W   X   Y   Z
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20

2    10
3    14
4    18
Name: X, dtype: int32

2    10
3    14
4    18
Name: X, dtype: int32


In [64]:
data = {
    'Company': ['SCG', 'SCG', 'PTT', 'PTT', 'KTB', 'KTB'],
    'Person': list("ABCDEF"),
    'Sales': [200, 300, 450, 100, 140, 350]
}
df = pd.DataFrame(data)
print(df)

# groupby คือการจัดกลุ่มข้อมูลในแนวแกน X โดยใช้คำสั่ง groupby() และสามารถใช้คำสั่ง sum(), mean(), describe() ได้

# df.groupby('Company').sum()
# print(df.groupby('Company'))
# print(df.groupby('Company').describe())

  Company Person  Sales
0     SCG      A    200
1     SCG      B    300
2     PTT      C    450
3     PTT      D    100
4     KTB      E    140
5     KTB      F    350


In [33]:
print(df.groupby('Company').describe().transpose()['PTT'])

Sales  count      2.000000
       mean     275.000000
       std      247.487373
       min      100.000000
       25%      187.500000
       50%      275.000000
       75%      362.500000
       max      450.000000
Name: PTT, dtype: float64


In [69]:
print(df['Company'].unique()) # แสดงค่าที่ไม่ซ้ำกัน
print(df['Company'].nunique()) # แสดงจำนวนค่าที่ไม่ซ้ำกัน
print(df['Company'].value_counts()) # แสดงจำนวนค่าที่ซ้ำกัน

['SCG' 'PTT' 'KTB']
3
SCG    2
PTT    2
KTB    2
Name: Company, dtype: int64


In [35]:
df[df['Sales'] == 200]
df['Sales'].max()
df['Sales'].min()
df['Sales'].apply(lambda x: x*2)
df['Sales'].apply(lambda x: x*2).sum()

3080

อยู่กับไฟล์ดูที่ไฟล์ lab/001/

In [36]:
import pandas as pd
df = pd.read_excel('./001/Sample - Superstore.xls')
# print(df)
# print(df['Discount'] == df['Discount'].max())
print(df['Category'].unique())
# print(df.groupby('Category').sum()['Sales'])

['Furniture' 'Office Supplies' 'Technology']


In [37]:
# binary counter
import numpy as np
import pandas as pd
def binary_counter(n) -> list:
    return [[int(i) for i in format(j, '0' + str(n) + 'b')] for j in range(2**n)]
n = 10
df = pd.DataFrame(binary_counter(n), columns=[f'bit{i}' for i in range(n)])
df.to_csv('./001/binary_counter.csv', index=False)
df['sum'] = df.apply(lambda x: x.sum(), axis=0)

In [38]:
def lenda_test(n) -> list:
    return [[int(i) for i in format(j, '0' + str(n) + 'b')] for j in range(2**n)]
print(lenda_test(3))

[[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]]


In [39]:
import numpy as np
import pandas as pd

In [40]:
df = pd.DataFrame(np.random.randint(10, 50, (5, 4)), index='a b c d e'.split()
                  ,columns = 'W X Y Z'.split())
df

W   X   Y   Z
a  33  44  19  10
b  30  45  44  14
c  25  21  31  40
d  40  40  29  43
e  46  48  18  19

add new column

In [41]:
# drop axis=0 คือ drop row
# drop axis=1 คือ drop column
# inplace=True คือ ทำการเปลี่ยนแปลงตารางเดิม
if 'SUM_Y' in df.index:
    df.drop('SUM_Y', axis=0, inplace=True)

if 'SUM_X' in df.columns:
    df.drop('SUM_X', axis=1, inplace=True)

df['SUM_X'] = df.apply(lambda x: x.sum(), axis=1)
df.loc['SUM_Y'] = df.apply(lambda x: x.sum(), axis=0)
df

W    X    Y    Z  SUM_X
a       33   44   19   10    106
b       30   45   44   14    133
c       25   21   31   40    117
d       40   40   29   43    152
e       46   48   18   19    131
SUM_Y  174  198  141  126    639

rename name of column

In [42]:
# rename row
df.rename(index={'SUM_Y': 'SUM_XYZ'}, inplace=True)
# rename column
df.rename(columns={'W': 'W1', 'X': 'X1', 'Y': 'Y1', 'Z': 'Z1'}, inplace=True)
df

W1   X1   Y1   Z1  SUM_X
a         33   44   19   10    106
b         30   45   44   14    133
c         25   21   31   40    117
d         40   40   29   43    152
e         46   48   18   19    131
SUM_XYZ  174  198  141  126    639

In [43]:
# reset_index จะทำให้ index กลายเป็น column ใหม่
# drop=True คือ ไม่ต้องเก็บ index เก่าไว้
# inplace=True คือ ทำการเปลี่ยนแปลงตารางเดิม
df.reset_index(drop=True, inplace=True)
df


W1   X1   Y1   Z1  SUM_X
0   33   44   19   10    106
1   30   45   44   14    133
2   25   21   31   40    117
3   40   40   29   43    152
4   46   48   18   19    131
5  174  198  141  126    639

In [44]:
df.rename(columns={'index': 'ID'}, inplace=True)
df

W1   X1   Y1   Z1  SUM_X
0   33   44   19   10    106
1   30   45   44   14    133
2   25   21   31   40    117
3   40   40   29   43    152
4   46   48   18   19    131
5  174  198  141  126    639

In [45]:
df.set_index('ID', inplace=True)
df

KeyError: "None of ['ID'] are in the columns"

In [ ]:
df.loc['SUM_XYZ'] = df.apply(lambda x: x.sum(), axis=0)
df

A     B    C
ID                     
0        1.0   5.0  1.0
1        2.0   5.0  2.0
2        1.5   5.0  3.0
SUM_XYZ  4.5  15.0  6.0

In [ ]:
d = {
    'A': [1,2,np.nan],
    'B': [5,np.nan,np.nan],
    'C': [1,2,3]
    }
df = pd.DataFrame(d)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
# df.dropna(axis=0, inplace=True)
# df.info()
# df.dropna()

# thresh=2 คือ ถ้ามีค่า NaN มากกว่า 2 ค่า จะ drop ทิ้ง
df.dropna(thresh=2, inplace=True)
df

# axis=0 คือ แถว
# axis=1 คือ คอลัมน์

df.dropna(axis=1, inplace=True)
df

A  C
0  1.0  1
1  2.0  2

In [70]:
d = {
    'A': [1,2,np.nan],
    'B': [5,np.nan,np.nan],
    'C': [1,2,3]
    }
df = pd.DataFrame(d)
display(df)
def mean_test(x):
    return x.mean()
df.fillna(value= df.apply(mean_test), inplace=True)
display(df)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

In [ ]:
df1 = pd.DataFrame({    'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df2 = pd.DataFrame({    'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'E': ['D4', 'D5', 'D6', 'D7']},
                        index=[4, 5, 6, 7])
df3 = pd.DataFrame({    'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'E': ['D8', 'D9', 'D10', 'D11']},
                        index=[4, 5, 6, 7])

# concat จะเป็นการต่อตาราง โดยจะต่อตารางที่มี index เดียวกัน
pd2 = pd.concat([df1, df2, df3], axis=0)
pd2


A    B    C    D    E
0   A0   B0   C0   D0  NaN
1   A1   B1   C1   D1  NaN
2   A2   B2   C2   D2  NaN
3   A3   B3   C3   D3  NaN
4   A4   B4   C4  NaN   D4
5   A5   B5   C5  NaN   D5
6   A6   B6   C6  NaN   D6
7   A7   B7   C7  NaN   D7
4   A8   B8   C8  NaN   D8
5   A9   B9   C9  NaN   D9
6  A10  B10  C10  NaN  D10
7  A11  B11  C11  NaN  D11

In [ ]:
pfall = pd.concat([df1, df2, df3], axis=1)
pfall

A    B    C    D    A    B    C    E    A    B    C    E
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4   A8   B8   C8   D8
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5   A9   B9   C9   D9
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6  A10  B10  C10  D10
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7  A11  B11  C11  D11

In [ ]:
(pfall['A'] == 'A0') & (pfall['B'] == 'B0')

C:\Users\puemm\AppData\Local\Temp\ipykernel_19420\1348370778.py:1: FutureWarning: reindexing with a non-unique Index is deprecated and will raise in a future version.
  pfall[


ValueError: cannot reindex on an axis with duplicate labels