# Data Structure Final

## Python for Beginner

Python print

In [80]:
print("Welcome to Python FAH Structures")
print("Welcome to Kasetsart University")
print("Welcome to Python Data Structures")

Welcome to Python FAH Structures
Welcome to Kasetsart University
Welcome to Python Data Structures


Python Variables

In [81]:
a = 10 # a is an integer
b = 10.5 # b is a float
c = "Hello" # c is a string
d = True # d is a boolean

e = [1, 2, 3, 4, 5] # list
f = (1, 2, 3, 3, 5) # tuple
g = {"name": "John", "age": 30} # dictionary
h = {1, 2, 3, 4, 5, 6} # set

print(f"a = {a}, b = {b}, c = {c}, d = {d}")
print("a = %d, b = %f, c = %s, d = %s" % (a, b, c, d))

a = 10, b = 10.5, c = Hello, d = True
a = 10, b = 10.500000, c = Hello, d = True


Arithmetic Operators

In [82]:
a = 9
b = 3
print("Arithmetic Operators")
print("a + b = %d" % (a + b))
print("a - b = %d" % (a - b))
print("a * b = %d" % (a * b))
print("a / b = %f" % (a / b))
print("a // b = %d" % (a // b))
# print("a % b = %d" % (a % b))
print("a ** b = %d" % (a ** b))

Arithmetic Operators
a + b = 12
a - b = 6
a * b = 27
a / b = 3.000000
a // b = 3
a ** b = 729


Comparison Operators

In [83]:
a: int = 10 
b: int = 3
print("Comparison Operators")
print(f"a > b = {a > b}")
print(f"a < b = {a < b}")
print(f"a == b = {a == b}")
print(f"a != b = {a != b}")
print(f"a >= b = {a >= b}")
print(f"a <= b = {a <= b}")

Comparison Operators
a > b = True
a < b = False
a == b = False
a != b = True
a >= b = True
a <= b = False


Assignments Operators

In [84]:
print("Assignments Operators")
a = 10 
b = 3
a += b
# a = a + b
print(f"a += b = {a}")
a = 10 
b = 3
a -= b
# a = a - b
print(f"a -= b = {a}")
a = 10 
b = 3
a *= b
# a = a * b
print(f"a *= b = {a}")
a = 10 
b = 3
a /= b
# a = a / b
print(f"a /= b = {a}")
a = 10 
b = 3
a %= b
# a = a % b
print(f"a %= b = {a}")
a = 10 
b = 3
a //= b
# a = a // b
print(f"a //= b = {a}")
a = 10 
b = 3
a **= b
# a = a ** b
print(f"a **= b = {a}")

Assignments Operators
a += b = 13
a -= b = 7
a *= b = 30
a /= b = 3.3333333333333335
a %= b = 1
a //= b = 3
a **= b = 1000


Logical Operators

In [85]:
e = True
f = False
# e = [6,7,6,5]
# f = [6,7,1]
print("Logical Operators")
print(f"e and f = {e and f}")
print(f"e or b = {e or f}")
print(f"not e = {not e}")

Logical Operators
e and f = False
e or b = True
not e = False


Membership Operators

In [86]:
a = 10
b = [1, 2, 3, 4, 5]
print("Membership Operators")
print(f"a in b = {a in b}")
print(f"a not in b = {a not in b}")

Membership Operators
a in b = False
a not in b = True


Identity Operators

In [87]:
a = 10
b = 10
print("Identity Operators")
print(f"a is b = {a is b}")
print(f"a is not b = {a is not b}")

Identity Operators
a is b = True
a is not b = False


If else statement

In [88]:
inp = int(input())
if inp > 5:
    print("inp > 5")
elif inp == 5:
    print("inp == 5")
else:
    print("inp < 5")

ValueError: invalid literal for int() with base 10: 'asdasdasd'

Loop statement

In [ ]:
for i in range(10):
    print(i, end=" ")

start = 0
stop = 10
step = 2
for i in range(start, stop, step):
    print(i)

for i in range(10):
    if i == 5:
        continue
    print(i, end=" ")

for i in range(10):
    if i == 5:
        break
    print(i, end=" ")

String slice

In [ ]:
name = "Tanapat Eiam-arj"
# print(name[0:5])
# print(name[3:5])
# print(name[0:5:2])
# print(name[0::])
print(name[-5:-1])


Lists

In [ ]:
# {} # dictionary
# {} # set
# [] # list
# () # tuple

# list
# a = [1, 2, 3, 4, 5]
# a = [5, 4, 3, 2, 1]
# a = [4, 5, 3, 1, 2, 2, 2]
# b = [5, 4, 3, 2, 1]
# a.pop()
# a.append(20)
# a.insert(1, 10)
# a.remove(6) // Value
# a.sort()
# a.reverse()
# print(a.count(2))

# Set
# a = {1, 2, 3, 4, 5}
# b = {5, 4, 3, 2, 1}
# a - b # a but not b
# a | b # a or b
# a & b # a and b
# a ^ b # a xor b

# I/O: open, close, read, write, append
# r = read
# w = write
# a = append
# r+ = read and write
# w+ = write and read
# a+ = append and read

# open = not file exist -> create file
# open = file exist -> open file

a = [4, 5, 3, 1, 2, "20", 2]
b = (10, "Anime", 3.14 , True)
print(a[0])
print(b[0])

c = {"name": "John", "age": 30}
print(c.get("name"))

Function

In [ ]:
# def hello():
    # print("Hello World")

# def hello(str):
#     print(str)

def hellos(*str):
    print(str)
def hello(**str):
    print(str)

hellos("Hello", "World", "Python")
hello(name="John", age=30, power=100)

Class

In [ ]:
class Name:
    def __init__(self, name):
        self.name = name

    def say(self):
        self.korn = 'asdasd'
        print(f"Hello {self.name}")

    def love(self):
        print(f"AAA {self.korn}")

name = Name("John")
name.say()
name.love()

In [ ]:

with open('txt.csv', 'w') as f:
    # f.write("Anime")
    for i in range(100):
        f.write(f"Anime = {i}\n")


## Python Numpy

Numpy

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
print(a) # array([1, 2, 3, 4, 5])

[1 2 3 4 5]


In [ ]:
n = np.ones((5, 5) ,dtype=int)
print(n) # array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
a = np.arange(10)
print(a)

a = np.arange(0, 10)
print(a)

a = np.arange(0, 10, 2)
print(a)

a = np.arange(100, 10, -5, dtype=int)
print(a)

a = np.linspace(100, 0 ,5)
print(a)




[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[100  95  90  85  80  75  70  65  60  55  50  45  40  35  30  25  20  15]
[100.  75.  50.  25.   0.]


In [ ]:
import pandas as pd

a = np.eye(5, dtype=int)
print("np eye 5")
print(a)

a = np.eye(5, 8, dtype=int)
print("np eye 5, 8")
print(a)

a = np.eye(8, 8, -2, dtype=int)
print("np eye 5, 8, -2")
print(a)


a = np.eye(5, 8, k=1, dtype=int)
print("np eye 5, 8, k=1")
print(a)

a = np.eye(5, 8, k=-1, dtype=int)
print("np eye 5, 8, k=-1")
print(a)

a = np.eye(5, 8, k=2, dtype=int)
print("np eye 5, 8, k=2")
print(a)



np eye 5
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
np eye 5, 8
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]]
np eye 5, 8, -2
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]
np eye 5, 8, k=1
[[0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]
np eye 5, 8, k=-1
[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]
np eye 5, 8, k=2
[[0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]]


In [ ]:
a = np.empty((5, 5))
# print(a)

last = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10
]

a = np.random.choice(last , p=[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05,0.05, 0.2], size=(4, 5))
print(a)

a = np.reshape(a, (5, 4))
print(a)

[[ 4  9  5  1  3]
 [ 1  7  9  9  9]
 [ 7  8 10  2  4]
 [10  1  6  5  2]]
[[ 4  9  5  1]
 [ 3  1  7  9]
 [ 9  9  7  8]
 [10  2  4 10]
 [ 1  6  5  2]]


In [ ]:
from numpy import random as rd
a = np.arange(10)
print(a)
b = rd.shuffle(a)
print(b)
c = rd.permutation(a)
print(c)

[0 1 2 3 4 5 6 7 8 9]
None
[6 8 9 7 0 1 4 3 5 2]


vactor in numpy

In [ ]:
import numpy as np

L1 = [1, 2, 3, 4, 5]
L2 = [5, 4, 3, 2, 1]
L3 = np.array(L1) + np.array(L2)
print(L3)
L4 = [x+y for x, y in zip(L1, L2)]
print(L4)
L5 = lambda x, y: x+y
L5 = [x for x in L5(L1, L2)]
print(L5)

[6, 6, 6, 6, 6]
[6 6 6 6 6]


## Python: Pandas

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
s = pd.Series([5,20,30,35,60], index=['a','b','c','d','e'])
print(f"Series\n{s}\n")


Series
a     5
b    20
c    30
d    35
e    60
dtype: int64



In [ ]:
sf1 = pd.DataFrame(np.random.randint(10, 50, [5,4]))
print(f"แบบไม่กำหนด Row กับ Column\n {sf1} \n")

sf2 = pd.DataFrame(np.random.randint(10, 50, [5,4]), columns=list('abcd'), index=list('abcde'))
print(f"แบบกำหนด Row กับ Column\n {sf2} \n")

แบบไม่กำหนด Row กับ Column
     0   1   2   3
0  10  28  44  11
1  40  19  35  49
2  21  11  48  14
3  19  26  34  11
4  27  23  44  32 

แบบกำหนด Row กับ Column
     a   b   c   d
a  25  40  20  49
b  31  16  14  13
c  46  10  36  33
d  27  44  21  41
e  43  45  23  15 



Accessing Data

In [ ]:
sf3 = pd.DataFrame(np.random.randint(10, 50, [5,4]), columns=list('abcd'), index=list('abcde'))
print(f"{sf3} \n")
print(f"การเข้าถึง data ใน DataFrame: sf3['a']\n{sf3['a']} \n")
print(f"การเข้าถึง data ใน DataFrame แบบเลือก Column: sf3['a'][2] \n{sf3['a'][2]} \n")
# loc
print(f"การเข้าถึง data ใน DataFrame แบบ loc: sf3.loc['a'] \n{sf3.loc['a']} \n")
print(f"การเข้าถึง data ใน DataFrame แบบ loc แบบเลือก Column: sf3.loc['a']['a']\n{sf3.loc['a']['a']} \n")
# iloc
print(f"การเข้าถึง data ใน DataFrame แบบ iloc: sf3.iloc[0] \n{sf3.iloc[0]} \n")
print(f"การเข้าถึง data ใน DataFrame แบบ iloc แบบเลือก Column: : sf3.iloc[0][0] \n{sf3.iloc[0][0]} \n")
# access
print(f"การเข้าถึง data ใน DataFrame แบบ access: sf3.a \n{sf3.a} \n")
print(f"การเข้าถึง data ใน DataFrame แบบ access แบบเลือก Column: sf3.a[0] \n{sf3.a[0]} \n")
print(f"การเข้าถึง data ใน DataFrame แบบ access แบบเลือกหลาย Column : sf3[['a','b']] \n{sf3[['a','b']]} \n")

In [90]:
df = pd.DataFrame(np.arange(1,21).reshape(5,4), columns=list('WXYZ'))
print(df)

    W   X   Y   Z
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


In [91]:
print(f"\n{df.loc[1::2, 'X':'Z']}")


    X   Y   Z
1   6   7   8
3  14  15  16


In [92]:
print(f"\n{df.loc[1::2, 'X':'Z']}")


    X   Y   Z
1   6   7   8
3  14  15  16


In [93]:
print(f"\n{df[df>5]}")


      W     X     Y     Z
0   NaN   NaN   NaN   NaN
1   NaN   6.0   7.0   8.0
2   9.0  10.0  11.0  12.0
3  13.0  14.0  15.0  16.0
4  17.0  18.0  19.0  20.0


In [ ]:
print(f"\n{df['W'] > 5}")
print(f"\n{df[df['W'] > 5]}")
print(f"\n{df[df['W'] > 5]['X']}")
# print(f"\n{df[df['W'] > 5].loc['X']}")
print(f"\n{df[df['W'] > 5].iloc[:, 1]}")

In [ ]:
data = {
    'Company': ['SCG', 'SCG', 'PTT', 'PTT', 'KTB', 'KTB'],
    'Person': list("ABCDEF"),
    'Sales': [200, 300, 450, 100, 140, 350]
}
df = pd.DataFrame(data)
print(df)
# df.sum()
# df.groupby('Company').sum()
# df.groupby('Company').mean()
print(df.groupby('Company').describe())

  Company Person  Sales
0     SCG      A    200
1     SCG      B    300
2     PTT      C    450
3     PTT      D    100
4     KTB      E    140
5     KTB      F    350
        Sales                                                      
        count   mean         std    min    25%    50%    75%    max
Company                                                            
KTB       2.0  245.0  148.492424  140.0  192.5  245.0  297.5  350.0
PTT       2.0  275.0  247.487373  100.0  187.5  275.0  362.5  450.0
SCG       2.0  250.0   70.710678  200.0  225.0  250.0  275.0  300.0


In [ ]:
print(df.groupby('Company').describe().transpose()['PTT'])

Sales  count      2.000000
       mean     275.000000
       std      247.487373
       min      100.000000
       25%      187.500000
       50%      275.000000
       75%      362.500000
       max      450.000000
Name: PTT, dtype: float64


In [ ]:
print(df['Company'].unique()) # แสดงค่าที่ไม่ซ้ำกัน
print(df['Company'].nunique()) # แสดงจำนวนค่าที่ไม่ซ้ำกัน
print(df['Company'].value_counts()) # แสดงจำนวนค่าที่ซ้ำกัน

['SCG' 'PTT' 'KTB']
3
SCG    2
PTT    2
KTB    2
Name: Company, dtype: int64


In [ ]:
df[df['Sales'] == 200]
df['Sales'].max()
df['Sales'].min()
df['Sales'].apply(lambda x: x*2)
df['Sales'].apply(lambda x: x*2).sum()

3080

อยู่กับไฟล์ดูที่ไฟล์ lab/001/

In [ ]:
import pandas as pd
df = pd.read_excel('./001/Sample - Superstore.xls')
print(df)
# print(df['Discount'] == df['Discount'].max())
# print(df['Category'].unique())
print(df.groupby('Category').sum()['Sales'])

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class   
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class   
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class   
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class   
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class   
...      ...             ...        ...        ...             ...   
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class   
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class   

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson 

In [ ]:
# binary counter
import numpy as np
import pandas as pd

def binary_counter(n):
    return [[int(i) for i in format(j, '0' + str(n) + 'b')] for j in range(2**n)]

def generator() -> list:
   yield ["0", "1"]
   yield ["2", "3"]
   yield ["4", "5"]

for i in generator():
    generato = generator()
    for i in generato:
        print(i)

['0', '1']
['2', '3']
['4', '5']
['0', '1']
['2', '3']
['4', '5']
['0', '1']
['2', '3']
['4', '5']
