@PuemMTH

In [1]:
# - List: () Tuple: ()
# - Dict: {} Set: {}

e = [1, 2, 3, 4, 5] # list
f = (1, 2, 3, 3, 5) # tuple
g = {"name": "John", "age": 30} # dictionary
h = {1, 2, 3, 4, 5, 6} # set

# Opertators
# - Arithmetic: + - * / % ** //
# - Assignment: = += -= *= /= %= **= //=
# - Comparison: == != > < >= <=
# - Logical: and or not
# - Identity: is is not
# - Membership: in not in
# - Bitwise: & | ^ ~ << >>

$Numpy$

In [2]:
import numpy as np

# List to nbarray
a = np.array([1, 2, 3, 4, 5])

# Ones คือ สร้าง array ขนาด 5x5 ที่เต็มด้วย 1 
b = np.ones((5, 5) ,dtype=int)

# Zeros คือ สร้าง array ขนาด 5x5 ที่เต็มด้วย 0
c = np.zeros((5, 5) ,dtype=int)

# Full คือ สร้าง array ขนาด 5x5 ที่เต็มด้วย จำนวนที่กำหนด
d = np.full((5, 5), 5, dtype=int)

# Eye คือ สร้าง array ขนาด 5x5 ที่เต็มด้วย 0 และ 1 ตามเส้นทแยงมุม
e = np.eye(5, dtype=int)
# array([[0., 1., 0.],
#        [0., 0., 1.],
#        [0., 0., 0.],
#        [0., 0., 0.]])
e_1 = np.eye(4, 3, 1)

# Arange คือ สร้าง array ที่เริ่มต้นที่ 1 จบที่ 10 และข้ามทีละ 2
g = np.arange(1, 10, 2)

# Linspace คือ สร้าง array ที่เริ่มต้นที่ 1 จบที่ 10 และมีจำนวน 5 ตัว
h = np.linspace(1, 10, 5)

# Reshape คือ แปลงจาก x,y ให้เป็น y,x ตามที่กำหนด
# เช่น จาก 1,9 ให้เป็น 3,3 แต่ต้องมีจำนวนเท่ากัน
# [1 2 3 4 5 6 7 8 9]
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
i = np.arange(1, 10).reshape(3, 3)

# Flatten คือ แปลงจาก y,x ให้เป็น x,y ตามที่กำหนด
# เช่น จาก 3,3 ให้เป็น 1,9
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
# [1 2 3 4 5 6 7 8 9]
j = np.arange(1, 10).reshape(3, 3).flatten()

display(a, b, c, d, e, e_1, g, h, i, j)

array([1, 2, 3, 4, 5])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

array([1, 3, 5, 7, 9])

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
from numpy import random

# Random คือ สร้าง array ขนาด 5x5 ที่เต็มด้วย จำนวนสุ่ม
# Parameter 1 คือ จำนวนต่ำสุด 2 คือ จำนวนสูงสุด 3 คือ ขนาดของ array
a = random.randint(1, 10, size=(5, 5)).flatten()

# สร้าง array ขนาด 5x5 ที่เต็มด้วย จำนวนสุ่ม จาก list ที่กำหนด
b = random.choice([1, 2, 3, 4, 5], size=(5, 5))

# สร้าง array ขนาด 5x5 ที่เต็มด้วย จำนวนสุ่ม จาก list ที่กำหนด โดยไม่ซ้ำกัน
rds = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
c = random.choice(rds, size=(3, 3), replace=False)

last = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
a = np.random.choice(last , p=[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05,0.05, 0.2], size=(4, 5))
print(a)


[[ 1 10  6  5 10]
 [10  4 10  2  2]
 [10  5  3  5  3]
 [ 5  4  9  3  7]]


In [4]:
# Shuffle คือ สลับตำแหน่งของ array ที่กำหนด
# จะเปลี่ยนค่าตัวแปรเดิม
# [1....10] to [ random number in array ]
d = np.arange(1, 10)
random.shuffle(d)
# d array([9, 6, 7, 8, 3, 4, 2, 5, 1])

# Permutation คือ สลับตำแหน่งของ array ที่กำหนด
# จะไม่เปลี่ยนค่าตัวแปรเดิม
e = np.arange(1, 10)
f = random.permutation(e)
g = random.permutation(e)
# e array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# f array([9, 4, 5, 8, 7, 6, 2, 1, 3])
# g array([1, 5, 9, 3, 4, 6, 8, 2, 7])

In [5]:
a1 = np.eye(5, 5, k=0, dtype=int)
a2 = np.eye(5, 5, k=-1, dtype=int)
# array([[False,  True,  True,  True,  True],
#        [False, False,  True,  True,  True],
#        [ True, False, False,  True,  True],
#        [ True,  True, False, False,  True],
#        [ True,  True,  True, False, False]])
a1 == a2

array([[False,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [ True, False, False,  True,  True],
       [ True,  True, False, False,  True],
       [ True,  True,  True, False, False]])

$Pandas$

In [6]:
import pandas as pd
import numpy as np

Series and DataFrames

In [7]:
# สร้าง DataFrame จาก list
# index คือ ชื่อ index ของแต่ละ row
# columns คือ ชื่อ column ของแต่ละ column
# Series คือ แปลง list ให้เป็น DataFrame
s = pd.Series([5,20,30,35,60], index=['a','b','c','d','e'])

# สร้าง DataFrame จาก array
df = pd.DataFrame([5,20,30,35,60], columns=['data'])

# DataFrame แบบกำหนด index และ column
sf2 = pd.DataFrame(np.random.randint(10, 50, [5,4]), 
                            columns=list('abcd'), 
                            index=list('efghi'))

Accessing data

In [8]:
acc_data = pd.DataFrame(np.random.randint(10, 50, [5,4]), 
                            columns=list('abcd'), 
                            index=list('efghi'))

# loc คือ ดึงข้อมูลจาก name row ที่กำหนด
# iloc คือ ดึงข้อมูลจาก index ที่กำหนด

display(acc_data)
#   a	b	c	d
# e	26	38	29	48
# f	26	46	40	29
# g	28	19	18	33
# h	28	29	31	32
# i	36	17	17	20

# log ดึงข้อมูลจาก row ที่กำหนด สามารถทำแบบ [start, stop, step] ได้
display(acc_data.loc['e': 'f'])
#    a	b	c	d
# e	26	38	29	48
# f	26	46	40	29

# log ดึงข้อมูลจาก row ที่กำหนด และ column ที่กำหนด
display(acc_data.loc['e', 'a'])
# 31

# iloc ดึงข้อมูลจาก index ที่กำหนด สามารถทำแบบ [start, stop, step] ได้
display(acc_data.iloc[0:2])

#   a	b	c	d
# e	29	36	45	47
# f	11	34	28	13
# iloc ดึงข้อมูลจาก index ที่กำหนด และ column ที่กำหนด
display(acc_data.iloc[0, 0])
# 29


a   b   c   d
e  17  12  32  28
f  49  18  24  14
g  24  34  18  14
h  37  17  45  41
i  28  18  15  26

a   b   c   d
e  17  12  32  28
f  49  18  24  14

17

a   b   c   d
e  17  12  32  28
f  49  18  24  14

17

Comparing data

In [9]:
# Comparing data
# สร้าง DataFrame จาก array

se = np.array( [35,37,36,40,
                31,46,37,45,
                34,15,40,47,
                13,46,39,36,
                45,19,44,13]).reshape(5,4)
df = pd.DataFrame(se, columns=list('abcd'), index=list('efghi'))

# df[row_condition][column_condition]
display(df[df > 35][df < 40])
#       a     b   c     d
# e   NaN  37.0  36  40.0
# f   NaN  46.0  37  45.0
# g   NaN   NaN  40  47.0
# h   NaN  46.0  39  36.0
# i  45.0   NaN  44   NaN

# [start, stop, step]
# ndarray
display(se[:, 1:3])
# [37, 46, 15, 46, 19], [36, 37, 40, 39, 44]

# DataFrame
display(df.iloc[:, 1:3])
#   b	c
# e	37	36
# f	46	37
# g	15	40
# h	46	39
# i	19	44



a     b     c     d
e NaN  37.0  36.0   NaN
f NaN   NaN  37.0   NaN
g NaN   NaN   NaN   NaN
h NaN   NaN  39.0  36.0
i NaN   NaN   NaN   NaN

array([[37, 36],
       [46, 37],
       [15, 40],
       [46, 39],
       [19, 44]])

b   c
e  37  36
f  46  37
g  15  40
h  46  39
i  19  44

In [10]:
data = {
    'Company': ['SCG', 'SCG', 'PTT', 'PTT', 'KTB', 'KTB'],
    'Person': list("ABCDEF"),
    'Sales': [200, 300, 450, 100, 140, 350]
}
df = pd.DataFrame(data)
print(df)
# df.sum()
# df.groupby('Company').sum()
# df.groupby('Company').mean()
# print(df.groupby('Company').describe())

  Company Person  Sales
0     SCG      A    200
1     SCG      B    300
2     PTT      C    450
3     PTT      D    100
4     KTB      E    140
5     KTB      F    350


In [11]:
# drop axis=0 คือ drop row
# drop axis=1 คือ drop column
# inplace=True คือ ทำการเปลี่ยนแปลงตารางเดิม

data = {
    'Company': ['SCG', 'SCG', 'PTT', 'PTT', 'KTB', 'KTB'],
    'Person': list("ABCDEF"),
    'Sales': [200, 300, np.nan, 100, 140, 350]
}
df = pd.DataFrame(data)

# Drop Column
df.drop('Person', axis=1, inplace=True)
# Drop Row
df.drop(4, axis=0, inplace=True)

# Apply function
def add_10(x):
    return x + 10

# Add new column
df['+10'] = df['Sales'].apply(add_10)

# Add new row 
df.loc[6] = ['SUM', df['Sales'].sum(), df['+10'].sum()]


# Fill NaN
df.fillna(value=df['Sales'].mean(), inplace=True)

# Sort
df.sort_values(by='Sales', ascending=True, inplace=True)

# Reset index
df.reset_index(inplace=True)

# Drop index
df.drop('index', axis=1, inplace=True)

# Rename column
df.rename(columns={'Sales': 'Sales (M)'}, inplace=True)

# Save to csv
df.to_csv('new.csv', index=False)

# Concat
df1 = pd.DataFrame({ 'A': ['A0', 'A1', 'A2', 'A3'], 'B': ['B0', 'B1', 'B2', 'B3'], 'C': ['C0', 'C1', 'C2', 'C3'], 'D': ['D0', 'D1', 'D2', 'D3']}, index=[0, 1, 2, 3])
df2 = pd.DataFrame({ 'A': ['A4', 'A5', 'A6', 'A7'], 'B': ['B4', 'B5', 'B6', 'B7'], 'C': ['C4', 'C5', 'C6', 'C7'], 'D': ['D4', 'D5', 'D6', 'D7']}, index=[4, 5, 6, 7])

display(df, pd.concat([df1, df2], axis=0))

Company  Sales (M)    +10
0     PTT      100.0  110.0
1     SCG      200.0  210.0
2     SCG      300.0  310.0
3     KTB      350.0  360.0
4     PTT      380.0  380.0
5     SUM      950.0  990.0

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

Pasdas: Examples

In [12]:
import pandas as pd
import numpy as np
from numpy.random import randn

In [13]:
ds = pd.read_csv('./ds_salaries.csv')

In [14]:
ds.head()
# ds.tail()
# ds.info()

Unnamed: 0  work_year experience_level employment_type  \
0           0       2020               MI              FT   
1           1       2020               SE              FT   
2           2       2020               SE              FT   
3           3       2020               MI              FT   
4           4       2020               SE              FT   

                    job_title  salary salary_currency  salary_in_usd  \
0              Data Scientist   70000             EUR          79833   
1  Machine Learning Scientist  260000             USD         260000   
2           Big Data Engineer   85000             GBP         109024   
3        Product Data Analyst   20000             USD          20000   
4   Machine Learning Engineer  150000             USD         150000   

  employee_residence  remote_ratio company_location company_size  
0                 DE             0               DE            L  
1                 JP             0               JP            S  
2                 GB            50               GB            M  
3                 HN             0               HN            S  
4                 US            50               US            L

In [15]:
display(ds[(ds['salary_currency'] == 'USD') & (ds['salary'] >= 260000)].tail(5)) 

display(ds[(ds['salary_currency'] == 'USD') & (ds['salary'] >= 260000)]['salary'].sum())



Unnamed: 0  work_year experience_level employment_type  \
416         416       2022               SE              FT   
482         482       2022               EX              FT   
519         519       2022               SE              FT   
523         523       2022               SE              FT   
534         534       2022               SE              FT   

                  job_title  salary salary_currency  salary_in_usd  \
416          Data Scientist  260000             USD         260000   
482           Data Engineer  324000             USD         324000   
519  Applied Data Scientist  380000             USD         380000   
523     Data Analytics Lead  405000             USD         405000   
534          Data Architect  266400             USD         266400   

    employee_residence  remote_ratio company_location company_size  
416                 US           100               US            M  
482                 US           100               US            M  
519                 US           100               US            L  
523                 US           100               US            L  
534                 US           100               US            M

5517400

In [16]:
def find(job_title):
    if 'Engineer' in job_title:
        return True
    else:
        return False
ds[ds['job_title'].apply(find)]
# ds[ds.job_title.str.contains('Engineer')]
# ds[ds.job_title.str.lower().str.contains('engineer')]
# ds[ds.job_title.str.lower().str.startswith('engineer')]
# ds[ds.job_title.str.lower().str.endswith('engineer')]
# ds[ds.job_title.str.lower().str.match('engineer')]

Unnamed: 0  work_year experience_level employment_type  \
2             2       2020               SE              FT   
4             4       2020               SE              FT   
9             9       2020               SE              FT   
16           16       2020               EN              FT   
17           17       2020               SE              FT   
..          ...        ...              ...             ...   
579         579       2022               SE              FT   
582         582       2022               SE              FT   
583         583       2022               SE              FT   
602         602       2022               SE              FT   
603         603       2022               SE              FT   

                     job_title   salary salary_currency  salary_in_usd  \
2            Big Data Engineer    85000             GBP         109024   
4    Machine Learning Engineer   150000             USD         150000   
9           Lead Data Engineer   125000             USD         125000   
16               Data Engineer  4450000             JPY          41689   
17           Big Data Engineer   100000             EUR         114047   
..                         ...      ...             ...            ...   
579              Data Engineer    25000             USD          25000   
582              Data Engineer   220110             USD         220110   
583              Data Engineer   160080             USD         160080   
602              Data Engineer   154000             USD         154000   
603              Data Engineer   126000             USD         126000   

    employee_residence  remote_ratio company_location company_size  
2                   GB            50               GB            M  
4                   US            50               US            L  
9                   NZ            50               NZ            S  
16                  JP           100               JP            S  
17                  PL           100               GB            S  
..                 ...           ...              ...          ...  
579                 US           100               US            M  
582                 US           100               US            M  
583                 US           100               US            M  
602                 US           100               US            M  
603                 US           100               US            M  

[230 rows x 12 columns]

In [17]:
val_ct = ds['experience_level'].value_counts()
display(val_ct)

val_unique = ds['experience_level'].unique()
display(val_unique)

val_nunique = ds['experience_level'].nunique()
display(val_nunique)

SE    280
MI    213
EN     88
EX     26
Name: experience_level, dtype: int64

array(['MI', 'SE', 'EN', 'EX'], dtype=object)

4

In [18]:
ds[ds['salary'].max() == ds['salary']] # ค่าสูงสุด
ds[ds['salary'].min() == ds['salary']] # ค่าต่ำสุด
ds[ds['salary'].mean() == ds['salary']] # ค่าเฉลี่ย

Empty DataFrame
Columns: [Unnamed: 0, work_year, experience_level, employment_type, job_title, salary, salary_currency, salary_in_usd, employee_residence, remote_ratio, company_location, company_size]
Index: []

In [19]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
ds['salary'].fillna(value = ds['salary'].mean() ,inplace = True )
