In [2]:
import numpy as np
import pandas as pd

In [3]:
lst = [1,2,3,4,5,6,7]
arr = np.array(lst)
display(lst)
display(arr)

[1, 2, 3, 4, 5, 6, 7]

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
one = np.ones((2,5), dtype=int)
display(one)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [5]:
zeros = np.zeros((2,5), dtype=int)
display(one)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
full = np.full((2,5), 20, dtype=int)
display(one)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
eye = np.eye(9,9,-3, dtype=int)
display(one)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
lst1 = [1,2,3,4,5,6,7]
lst2 = [1,2,3,4,5,6,2]
arr1 = np.array(lst1)
arr2 = np.array(lst2)

display(arr1,arr2, arr1 == arr2, arr1 & arr1)

array([1, 2, 3, 4, 5, 6, 7])

array([1, 2, 3, 4, 5, 6, 2])

array([ True,  True,  True,  True,  True,  True, False])

array([1, 2, 3, 4, 5, 6, 7], dtype=int32)

In [9]:
ranges = np.arange(0,20).reshape(5,4)
display(ranges)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
from numpy import random

In [11]:
sf = np.arange(0,20)
random.shuffle(sf)

sf_per = random.permutation(sf)
display(sf, sf_per)

array([12, 19,  5, 10, 13,  3, 17,  1, 18,  0,  9, 14,  2, 11,  4,  7,  6,
        8, 15, 16])

array([12, 19,  8, 13, 15,  3,  2, 10,  5,  7,  0, 16,  4, 14,  6, 18, 11,
       17,  1,  9])

In [12]:
ser = pd.Series([1,2,3,4,5], index=list('abcde'))
display(ser)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [13]:
pd.DataFrame([[1,2,3,4,5],[1,2,3,4,5]], index=list('ab'), columns=list('abcde'))

a  b  c  d  e
a  1  2  3  4  5
b  1  2  3  4  5

In [ ]:
food = pd.read_csv("./amazonFood.csv")
display(food.tail(5))

In [ ]:
def find_userid(user_id):
    return 'A3' in user_id
    
def find_review(comment):
    return 'GOOD'.lower() in str(comment).lower()

good_comment = food[food['Summary'].apply(find_review)]
display(good_comment.tail(2))

#food[food['UserId'].apply(find_userid)]
#food[food['Summary'].apply(find_review)]

In [ ]:
# good_comment['UserId'].value_counts()

all_comment = food[food['UserId'] == "AY12DBB0U420B"]["UserId"].count()
goods = good_comment[good_comment['UserId'] == "AY12DBB0U420B"]["UserId"].count()

display(all_comment, goods)

## Answer

นำเข้าข้อมูล csv ชื่อไฟล์ว่า amazonFood.csv
และลอง นำออกมาแสดง 5 ตัวอย่าง

In [56]:
food = pd.read_csv("./amazonFood.csv")
food.tail(5)

ProductId          UserId  \
41705  B007IVE938  A3MDETK0D5UAIN   
41706  B00125NESM   AGGS9IPJDU6ML   
41707  B003M5W8ZK  A373MY0PQL9R41   
41708  B003M5W8ZK  A3U2QUKGA7CJOP   
41709  B005GXGAGY  A33AYVATA17JUR   

                                             productName  Score  \
41705                 Ajika Organic Rose Buds, 1.6-Ounce      1   
41706   JOHN BOOS FBLG7224 Table,Stainless,Shelf,72"x24"      5   
41707  Green Mountain Coffee - Unsweetened Black Iced...      5   
41708  Green Mountain Coffee - Unsweetened Black Iced...      1   
41709  LATE JULY CHIP MLTIGRN GRNMOJO ORG, 5.5 OZ, PK...      5   

                             Summary  \
41705           Not what I expected.   
41706                        Great!!   
41707          Black tea v Coca Cola   
41708     Never Received the product   
41709  Great taste - and gluten free   

                                                    Text  
41705  I certainly could do better by these if I just...  
41706  Table is 35 inches in height.  It is heavy dut...  
41707  I have been one of those people that always fe...  
41708  I was charged for this product by Liquid Natio...  
41709  Everyone in my family loves this chip - from t...

นำข้อมูลที่ได้จาการ นำเข้า มา

 - หาความยาวของข้อความ Summary ถ้าน้อยกว่า 5 คำ (แสดง 2 ตัวอย่าง)

In [57]:
def find_word(word):
    word = str(word)
    if len(word.split(" ")) < 5:
        return False
    else:
        return True
    
food[food['Summary'].apply(find_word)].tail(2)

ProductId          UserId  \
41707  B003M5W8ZK  A373MY0PQL9R41   
41709  B005GXGAGY  A33AYVATA17JUR   

                                             productName  Score  \
41707  Green Mountain Coffee - Unsweetened Black Iced...      5   
41709  LATE JULY CHIP MLTIGRN GRNMOJO ORG, 5.5 OZ, PK...      5   

                             Summary  \
41707          Black tea v Coca Cola   
41709  Great taste - and gluten free   

                                                    Text  
41707  I have been one of those people that always fe...  
41709  Everyone in my family loves this chip - from t...

 - จากข้อก่อนหน้ามีกี่คนที่ให้ 5 คะแนนที่คน

In [58]:
a = food[food['Summary'].apply(find_word)]
b = a[a['Score'] == 5]['UserId']
display(b.value_counts().count())

7241

 - แสดง top 5 product Name ทั้งหมด ที่ในชื่อมีคำว่า Coffee

In [59]:
food[food['productName'].apply(lambda x: 'coffee' in x.lower())]['productName'].value_counts().head()

Wolfgang Puck Coffee, Chef's Reserve Colombian Decaf (Medium Roast), 24-Count K-Cups for Keurig Brewers (Pack of 2)    455
Puroast Low Acid Coffee French Roast, 2-Ounce Bag (Pack of 10)                                                         330
Green Mountain Coffee Roasters Breakfast Blend, Single-Serve Keurig K-Cup Pods, Light Roast Coffee Pods, 96 Count      242
Green Mountain Coffee Roasters Nantucket Blend, Single-Serve Keurig K-Cup Pods, Medium Roast Coffee, 96 Count          172
Emeril's Big Easy Bold Coffee, 108-Count K-Cup for Keurig Brewers                                                      150
Name: productName, dtype: int64

 - แสดงค่าเฉลี่ยคะแนนของคนที่ทานกาแฟ

In [60]:
food[food['productName'].apply(lambda x: 'coffee' in x.lower())]['Score'].mean()

4.131608548931384

 - แสดงจำนวนเมนูทั้งหมด ไม่นับชื่อเมนูที่ซ้ำกัน

In [61]:
len(food['productName'].unique())

4939

In [62]:
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41710 entries, 0 to 41709
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   ProductId    41710 non-null  object
 1   UserId       41710 non-null  object
 2   productName  41710 non-null  object
 3   Score        41710 non-null  int64 
 4   Summary      41708 non-null  object
 5   Text         41710 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.9+ MB


In [72]:
food.drop('Text', axis=1)

ProductId          UserId  \
0      B001E4KFG0  A3SGXH7AUHU8GW   
1      B00813GRG4  A1D87F6ZCVE5NK   
2      B000LQOCH0   ABXLMWJIXXAIN   
3      B000UA0QIQ  A395BORC6FGVXV   
4      B006K2ZZ7K  A1UQRSCLF8GW1T   
...           ...             ...   
41705  B007IVE938  A3MDETK0D5UAIN   
41706  B00125NESM   AGGS9IPJDU6ML   
41707  B003M5W8ZK  A373MY0PQL9R41   
41708  B003M5W8ZK  A3U2QUKGA7CJOP   
41709  B005GXGAGY  A33AYVATA17JUR   

                                             productName  Score  \
0            Dogswell Vitality Canned Dog Food Case Duck      5   
1      Southern Grove Premium Quality Roasted and Sal...      1   
2      Turkish Delight Filbert (Hazelnuts) (Sultan) 1...      4   
3      Faeries Finest Flavor Extract, Cherry, 2.04 Ounce      2   
4                     Salt Water Taffy - Assorted, 5 lbs      5   
...                                                  ...    ...   
41705                 Ajika Organic Rose Buds, 1.6-Ounce      1   
41706   JOHN BOOS FBLG7224 Table,Stainless,Shelf,72"x24"      5   
41707  Green Mountain Coffee - Unsweetened Black Iced...      5   
41708  Green Mountain Coffee - Unsweetened Black Iced...      1   
41709  LATE JULY CHIP MLTIGRN GRNMOJO ORG, 5.5 OZ, PK...      5   

                             Summary  
0              Good Quality Dog Food  
1                  Not as Advertised  
2              "Delight" says it all  
3                     Cough Medicine  
4                        Great taffy  
...                              ...  
41705           Not what I expected.  
41706                        Great!!  
41707          Black tea v Coca Cola  
41708     Never Received the product  
41709  Great taste - and gluten free  

[41710 rows x 5 columns]